spring:
  messages:
    encoding: UTF-8
  datasource:

    url: jdbc:mariadb://sihundb/kopling?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDB105Dialect


jwt:
  accessSecret: KhheB0euerVivwCL7P1WA0CL/N8Dt6EyQEa/Wi1XLaY5beneRnADC4KUQ+PAxMUBk8JuJvFl9mWk7zfkoNWlmA==
  refreshSecret: RGNVNSDJAdDVhbGRvb2HzJEAjIQ==acbhkashdbahskfbh

gauth:
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}

