spring:
  messages:
    encoding: UTF-8
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://sihundb/kopling?serverTimezone=Asia/Seoul
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  accessSecret: KhheB0euerVivwCL7P1WA0CL/N8Dt6EyQEa/Wi1XLaY5beneRnADC4KUQ+PAxMUBk8JuJvFl9mWk7zfkoNWlmA==
  refreshSecret: RGNVNSDJAdDVhbGRvb2HzJEAjIQ==acbhkashdbahskfbh

gauth:
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}

